### ISSUE TITLE
crashes as soon as it tries to download

### ISSUE THREAD

**Issue by nohkumado** [nv95/Kotatsu#145]
Hello
With the latest version(3.1) i don't seem to be able to download anymore, it crashes with :

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5a4bc87 u0 org.koitharu.kotatsu/.download.ui.service.DownloadService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:1965)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1936)
	at android.app.ActivityThread.access$2700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1876)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1831)
	at android.content.ContextWrapper.startForegroundService

**Comment by ztimms73** [comment]
Same as #50, update your app to latest verison 3.1.1.
