### ISSUE TITLE
Cannot access local Storage And Change downloads folder

### ISSUE THREAD

**Issue by danktememe** [nv95/Kotatsu#158]
### Steps to reproduce

- Go into settings
- Go Into content
- Tap Folder For Downloads
Or

- open local storage section

### Expected behavior

Able to see downloaded files and change directory

### Actual behavior

In the case of opening the local downloads section in the app it comes up with a error (without coming up with a black screen the app does not crash for this one) With the statment "Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference"

![image](https://user-images.githubusercontent.com/82302480/165865448-c980c52a-aa83-4c2a-b19b-0e8197f1e09d.png)

If I go and attempt to change the downloads directory the app will go into a back screen and come up a bunch of text

`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
    at org.koitharu.kotatsu.main.MainModuleKt$mainModule$1.invoke(Unknown Source:39)
    at kotlin.collections.CollectionsKtReversedViewsKt.filterInPlace$CollectionsKtMutableCollectionsKt(Unknown Source:15)
    at org.koitharu.kotatsu.local.data.LocalStorageManager.access$getConfiguredStorageDirs(Unknown Source:5)
    at org.koitharu.kotatsu.local.data.LocalStorageManager$getReadableDirs$2.invoke(Unknown Source:16)
    at org.koitharu.kotatsu.local.data.LocalStorageManager$getReadableDirs$2.invoke(Unknown Source:7)
    at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Unknown Source:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
    at kotlinx.coroutines.DispatchedTask.run(Unknown Source:4)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:6)`
Which is the error message

![image](https://user-images.githubusercontent.com/82302480/165865434-04bcda74-a741-4c91-b0c7-5170805b01ec.png)

### Kotatsu version

3.2 (also happened on 3.0)

### Android version

Android 11

### Device

Galaxy A32

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [parsers repository](https://github.com/nv95/kotatsu-parsers/issues/new).
- [X] I have updated the app to version **[3.2](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nv95** [comment]
Should be fixed, reopen if needed
