### ISSUE TITLE
Cannot read manga [Error]

### ISSUE THREAD

**Issue by Thewisem** [nv95/Kotatsu#35]
I wanted to read one piece chapter 1016. But then when I tried it thia error arrived

java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:PageHolder{e8f821c position=3 id=-4289199082711595803, oldPos=-1, pLpos:-1} 
 View Holder 2:PageHolder{ff0c497 position=6 id=-4289199082711595803, oldPos=-1, pLpos:-1} androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{a671e25 VFED..... ......ID 0,0-1024,768 #c}, adapter:org.koitharu.kotatsu.reader.ui.pager.standard.PagesAdapter@eb54bfa, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@db3b5ab, context:org.koitharu.kotatsu.reader.ui.ReaderActivity@e5205e0
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:63)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:8)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:954)
	at android.view.View.layout(View.java:19039)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2711)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2426)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7296)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:640)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by Thewisem** [comment]
Mangaread

**Comment by chailuhc** [comment]
Getting same issue starting around the same time today

**Comment by nv95** [comment]
There are some breaking changes on mangaread. Fixed, will be available in next release (coming soon)
